SCHEMA_VERSION = "STABILIS-PERSIST-v0.1"
SQLITE_SCHEMA = r'''
PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS organizations(id TEXT PRIMARY KEY,name TEXT NOT NULL,slug TEXT UNIQUE NOT NULL,status TEXT NOT NULL DEFAULT 'ACTIVE',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS brands(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES organizations(id),name TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS locations(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES organizations(id),brand_id TEXT REFERENCES brands(id),code TEXT NOT NULL,name TEXT NOT NULL,market TEXT,region TEXT,timezone TEXT,opened_on TEXT,service_model TEXT,square_feet REAL,seats INTEGER,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(organization_id,code));
CREATE TABLE IF NOT EXISTS profiles(id TEXT PRIMARY KEY,email TEXT UNIQUE,name TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS memberships(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES organizations(id),profile_id TEXT NOT NULL REFERENCES profiles(id),role TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'ACTIVE',created_at TEXT NOT NULL,UNIQUE(organization_id,profile_id));
CREATE TABLE IF NOT EXISTS membership_locations(membership_id TEXT NOT NULL REFERENCES memberships(id),location_id TEXT NOT NULL REFERENCES locations(id),PRIMARY KEY(membership_id,location_id));
CREATE TABLE IF NOT EXISTS raw_files(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES organizations(id),uploaded_by TEXT,filename TEXT NOT NULL,original_filename TEXT NOT NULL,content_type TEXT,size_bytes INTEGER NOT NULL,sha256 TEXT NOT NULL,storage_path TEXT NOT NULL,source_system TEXT,reporting_period TEXT,processing_status TEXT NOT NULL,schema_version TEXT NOT NULL,version_number INTEGER NOT NULL DEFAULT 1,replaces_file_id TEXT REFERENCES raw_files(id),uploaded_at TEXT NOT NULL,duplicate_decision TEXT,UNIQUE(organization_id,storage_path));
CREATE INDEX IF NOT EXISTS idx_raw_files_hash ON raw_files(organization_id,sha256);
CREATE TABLE IF NOT EXISTS ingestion_jobs(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES organizations(id),raw_file_id TEXT NOT NULL REFERENCES raw_files(id),state TEXT NOT NULL,started_at TEXT,completed_at TEXT,code_version TEXT,schema_version TEXT,errors_json TEXT NOT NULL DEFAULT '[]',warnings_json TEXT NOT NULL DEFAULT '[]',record_count INTEGER NOT NULL DEFAULT 0,idempotency_key TEXT NOT NULL UNIQUE,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS mapping_profiles(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES organizations(id),name TEXT NOT NULL,version INTEGER NOT NULL,mapping_json TEXT NOT NULL,status TEXT NOT NULL,created_at TEXT NOT NULL,created_by TEXT,UNIQUE(organization_id,name,version));
CREATE TABLE IF NOT EXISTS location_aliases(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES organizations(id),location_id TEXT NOT NULL REFERENCES locations(id),source_system TEXT,alias TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(organization_id,source_system,alias));
CREATE TABLE IF NOT EXISTS fiscal_calendars(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES organizations(id),name TEXT NOT NULL,calendar_type TEXT NOT NULL,year_start_month INTEGER,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS fiscal_periods(id TEXT PRIMARY KEY,calendar_id TEXT NOT NULL REFERENCES fiscal_calendars(id),fiscal_year INTEGER NOT NULL,period_number INTEGER NOT NULL,start_date TEXT NOT NULL,end_date TEXT NOT NULL,label TEXT NOT NULL,UNIQUE(calendar_id,fiscal_year,period_number));
CREATE TABLE IF NOT EXISTS normalized_records(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES organizations(id),location_id TEXT NOT NULL REFERENCES locations(id),period TEXT NOT NULL,record_type TEXT NOT NULL,source_file_id TEXT NOT NULL REFERENCES raw_files(id),source_row INTEGER NOT NULL,source_field TEXT,raw_json TEXT NOT NULL,normalized_json TEXT NOT NULL,transformation_notes TEXT,normalization_version TEXT NOT NULL,created_at TEXT NOT NULL,lineage_key TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS data_quality_runs(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES organizations(id),ingestion_job_id TEXT REFERENCES ingestion_jobs(id),score REAL,gate_state TEXT NOT NULL,validation_version TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS data_quality_issues(id TEXT PRIMARY KEY,data_quality_run_id TEXT NOT NULL REFERENCES data_quality_runs(id),organization_id TEXT NOT NULL REFERENCES organizations(id),issue_type TEXT NOT NULL,severity TEXT NOT NULL,source TEXT,location_id TEXT REFERENCES locations(id),period TEXT,record_ref TEXT,description TEXT NOT NULL,recommended_resolution TEXT,status TEXT NOT NULL DEFAULT 'OPEN',resolved_by TEXT,resolution TEXT,resolved_at TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS analysis_runs(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES organizations(id),period_start TEXT,period_end TEXT,input_manifest_json TEXT NOT NULL,calculation_engine_version TEXT NOT NULL,metric_dictionary_version TEXT NOT NULL,benchmark_version TEXT NOT NULL,scoring_version TEXT NOT NULL,confidence_version TEXT NOT NULL,opportunity_version TEXT NOT NULL,deduplication_version TEXT NOT NULL,code_version TEXT NOT NULL,status TEXT NOT NULL,shadow_mode INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,created_by TEXT,finalized_at TEXT);
CREATE TABLE IF NOT EXISTS metrics(id TEXT PRIMARY KEY,analysis_run_id TEXT NOT NULL REFERENCES analysis_runs(id),organization_id TEXT NOT NULL REFERENCES organizations(id),location_id TEXT REFERENCES locations(id),period TEXT NOT NULL,metric_name TEXT NOT NULL,value REAL,unit TEXT,formula_version TEXT NOT NULL,lineage_json TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(analysis_run_id,location_id,period,metric_name));
CREATE TABLE IF NOT EXISTS findings(id TEXT PRIMARY KEY,analysis_run_id TEXT NOT NULL REFERENCES analysis_runs(id),organization_id TEXT NOT NULL REFERENCES organizations(id),location_id TEXT REFERENCES locations(id),period TEXT,category TEXT NOT NULL,metric TEXT,current_value REAL,benchmark_value REAL,variance REAL,benchmark_source TEXT,severity TEXT,materiality TEXT,confidence_label TEXT,confidence_score REAL,status TEXT NOT NULL,evidence_json TEXT NOT NULL,root_cause_status TEXT,engine_payload_json TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS opportunities(id TEXT PRIMARY KEY,finding_id TEXT REFERENCES findings(id),analysis_run_id TEXT NOT NULL REFERENCES analysis_runs(id),organization_id TEXT NOT NULL REFERENCES organizations(id),location_id TEXT REFERENCES locations(id),opportunity_group_id TEXT NOT NULL,category TEXT NOT NULL,theoretical_opportunity REAL NOT NULL,recoverability_factor REAL,low_estimate REAL,base_estimate REAL,high_estimate REAL,annualized_value REAL,confidence_label TEXT,benchmark_source TEXT,assumptions_json TEXT NOT NULL,deduplication_status TEXT NOT NULL,calculation_version TEXT NOT NULL,engine_payload_json TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS recommendations(id TEXT PRIMARY KEY,analysis_run_id TEXT NOT NULL REFERENCES analysis_runs(id),finding_id TEXT REFERENCES findings(id),opportunity_id TEXT REFERENCES opportunities(id),organization_id TEXT NOT NULL REFERENCES organizations(id),location_id TEXT REFERENCES locations(id),title TEXT NOT NULL,description TEXT NOT NULL,evidence_json TEXT NOT NULL,expected_effect TEXT,implementation_effort TEXT,time_to_impact TEXT,priority TEXT,confidence_label TEXT,review_status TEXT NOT NULL,engine_narrative TEXT NOT NULL,analyst_narrative TEXT,created_by TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS review_events(id TEXT PRIMARY KEY,recommendation_id TEXT NOT NULL REFERENCES recommendations(id),organization_id TEXT NOT NULL REFERENCES organizations(id),reviewer_id TEXT,decision TEXT NOT NULL,original_payload_json TEXT NOT NULL,edited_payload_json TEXT,explanation TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS intelligence_snapshots(id TEXT PRIMARY KEY,analysis_run_id TEXT NOT NULL REFERENCES analysis_runs(id),organization_id TEXT NOT NULL REFERENCES organizations(id),payload_json TEXT NOT NULL,methodology_versions_json TEXT NOT NULL,reviewer_id TEXT NOT NULL,approved_at TEXT NOT NULL,content_hash TEXT NOT NULL,UNIQUE(analysis_run_id,content_hash));
CREATE TABLE IF NOT EXISTS reports(id TEXT PRIMARY KEY,intelligence_snapshot_id TEXT NOT NULL REFERENCES intelligence_snapshots(id),organization_id TEXT NOT NULL REFERENCES organizations(id),period TEXT,version INTEGER NOT NULL,template_version TEXT NOT NULL,methodology_versions_json TEXT NOT NULL,reviewer_id TEXT,release_status TEXT NOT NULL,report_content TEXT NOT NULL,content_hash TEXT NOT NULL,generated_at TEXT NOT NULL,UNIQUE(intelligence_snapshot_id,version));
CREATE TABLE IF NOT EXISTS actions(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES organizations(id),recommendation_id TEXT REFERENCES recommendations(id),location_id TEXT REFERENCES locations(id),title TEXT NOT NULL,status TEXT NOT NULL,baseline REAL,target REAL,start_date TEXT,due_date TEXT,leading_indicator TEXT,lagging_indicator TEXT,expected_financial_impact REAL,actual_financial_impact REAL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS calibration_events(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES organizations(id),finding_id TEXT REFERENCES findings(id),recommendation_id TEXT REFERENCES recommendations(id),engine_predicted INTEGER,analyst_agreed INTEGER,operator_agreed INTEGER,action_implemented INTEGER,estimated_opportunity REAL,realized_opportunity REAL,confidence_label TEXT,time_to_outcome_days INTEGER,notes TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS audit_events(id TEXT PRIMARY KEY,organization_id TEXT,actor_id TEXT,action TEXT NOT NULL,entity_type TEXT NOT NULL,entity_id TEXT,previous_state_json TEXT,new_state_json TEXT,request_metadata_json TEXT,created_at TEXT NOT NULL);
'''
